/**
 * TSICVIDIA Canonical Universes & Seed Data
 * "Milo Chronicles" Universe + Assets & Episodes
 */

import {
  Character,
  Episode,
  LocationItem,
  PropItem,
  ProviderAdapter,
  Universe,
  AssetLineageRecord,
} from '../types';

export const INITIAL_LOCATIONS: LocationItem[] = [
  {
    id: 'loc_cyber_gym',
    name: 'Neon Iron Fitness Gym',
    description: 'High-contrast modern gym with brushed steel, amber overhead neon tubes, and rack of chrome dumbbells.',
    category: 'interior',
    lighting: 'Amber neon rim light with deep charcoal shadow contours',
    atmosphere: 'Intense, rhythmic, slightly comedic high-energy environment',
    backgroundUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1000&auto=format&fit=crop',
    palette: ['#FF9F24', '#0F1216', '#222831', '#ECEFF1'],
  },
  {
    id: 'loc_coffee_shop',
    name: 'Monochrome Espresso Lab',
    description: 'Minimalist brutalist coffee counter with matte black espresso machine and warm teak wooden accents.',
    category: 'interior',
    lighting: 'Soft directional morning sunlight filtering through geometric blinds',
    atmosphere: 'Introspective, contemplative, dry wit sanctuary',
    backgroundUrl: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?q=80&w=1000&auto=format&fit=crop',
    palette: ['#1A1C20', '#D4A373', '#FAEDCD', '#333333'],
  },
  {
    id: 'loc_sunset_rooftop',
    name: 'Rooftop Helipad Lounge',
    description: 'Open skyline view over futuristic high-rises at golden hour with distant orange horizon haze.',
    category: 'exterior',
    lighting: 'Golden hour sunset gradient from amber to deep indigo violet',
    atmosphere: 'Cinematic climax, philosophical banter, spacious',
    backgroundUrl: 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?q=80&w=1000&auto=format&fit=crop',
    palette: ['#FF7E67', '#6C5CE7', '#1E1E2F', '#FDCB6E'],
  },
];

export const INITIAL_PROPS: PropItem[] = [
  {
    id: 'prop_espresso_cup',
    name: 'Matte Ceramic Espresso Cup',
    category: 'beverage',
    description: 'Signature cylindrical matte black ceramic cup with gold rim.',
    canonicalImage: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'prop_headphones',
    name: 'Acoustic Studio Cans',
    category: 'wearable',
    description: 'Silver and obsidian over-ear noise-cancelling monitor headphones resting around neck.',
    canonicalImage: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'prop_smart_pad',
    name: 'Holographic Slate',
    category: 'gadget',
    description: 'Slim bezel tablet projecting glowing amber production data manifests.',
    canonicalImage: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?q=80&w=600&auto=format&fit=crop',
  },
];

export const MILO_CHARACTER: Character = {
  id: 'char_milo',
  name: 'Milo Vance',
  aliases: ['Milo', 'The Observer'],
  ageBracket: '26-29',
  archetype: 'Deadpan Cynic / Modern Philosopher',
  personality: 'Perceptive, hyper-articulate, mildly exhausted by cultural trends, dry comedic timing.',
  role: 'Lead Protagonist & Host',
  description: 'A 28-year-old creator who breaks down absurd modern rituals with mathematically precise comedic timing.',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=600&auto=format&fit=crop',
  currentVersion: 'v3.2',
  versions: [
    {
      version: 'v3.2',
      characterId: 'char_milo',
      parentVersion: 'v3.1',
      createdAt: '2026-08-20T14:30:00Z',
      changeSummary: 'Refined jawline landmark anchor, tightened hoodie color gamut to Charcoal #1B1E23, updated voice speaking speed to 1.08x.',
      isLocked: true,
      visualDna: {
        face: 'Angular jawline, slight 5 o clock shadow stubble, high cheekbones, relaxed brows',
        hair: 'Dark coffee brown, textured disheveled taper fade with slight forehead fringe',
        hairColor: '#2B1E1A',
        skin: 'Warm olive undertone with subtle natural texture',
        eyes: 'Almond shaped amber-hazel, hooded upper eyelids, deadpan gaze',
        eyeColor: '#7A5C3D',
        bodyProportions: '6ft 0in, slender lean athletic build, slightly slouched posture',
        wardrobe: 'Heavyweight matte charcoal drop-shoulder hoodie with silver drawcord aglets, relaxed raw-hem tee underneath',
        accessories: ['Silver flat-curb chain', 'Matte black studio headphones around neck'],
        artStyle: 'Stylized cinematic realism with crisp edge fidelity and filmic micro-contrast',
        palette: ['#1B1E23', '#2B1E1A', '#FF9F24', '#7A5C3D', '#E2E8F0'],
        lineStyle: 'Subtle clean geometric silhouette bounding with soft interior shading',
        shading: 'Three-point studio lighting with amber key and cool cyan bounce',
        visualConstraints: [
          'Never render with slicked hair',
          'Avoid smiling teeth showing; keep smirk or deadpan lip line',
          'Hoodie drawstrings must maintain consistent silver metallic tips',
        ],
      },
      voiceProfile: {
        provider: 'ElevenLabs',
        voiceId: 'eleven_milo_canonical_v3',
        voiceName: 'Milo Vance (Baritone Dry Irony)',
        language: 'en-US',
        accent: 'Mid-Atlantic Urban Neutral',
        pitch: 0.95,
        speakingSpeed: 1.08,
        emotionalProfile: 'Controlled deadpan with subtle dynamic pitch drops on punchlines',
        stability: 0.78,
        similarityBoost: 0.85,
      },
      references: [
        { id: 'ref_milo_front', type: 'front', url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=600&auto=format&fit=crop', hash: 'sha256:88fa29e81' },
        { id: 'ref_milo_34', type: 'three_quarter', url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=600&auto=format&fit=crop', hash: 'sha256:77bc34e12' },
        { id: 'ref_milo_side', type: 'side', url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=600&auto=format&fit=crop', hash: 'sha256:44aa19f90' },
        { id: 'ref_milo_full', type: 'full_body', url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=600&auto=format&fit=crop', hash: 'sha256:99ff20a33' },
      ],
      poseLibrary: [
        {
          id: 'pose_bench_slouch',
          name: 'Bench Slouch Observation',
          canonicalImage: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?q=80&w=600&auto=format&fit=crop',
          category: 'sitting',
          landmarks: 'Spine curved 12 deg backward, elbows resting on knees, relaxed shoulders',
          semanticTags: ['cynical', 'observant', 'casual', 'seated'],
          compatibleAngles: ['medium / eye-level', 'close-up / 45-deg', 'low-angle / frontal'],
          compatibleWardrobe: ['charcoal hoodie', 'oversized tee'],
        },
        {
          id: 'pose_pointing_forward',
          name: 'Direct Precision Point',
          canonicalImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=600&auto=format&fit=crop',
          category: 'gesture',
          landmarks: 'Right index finger extended toward camera lens, left arm relaxed',
          semanticTags: ['emphasis', 'argument', 'punchline', 'breakdown'],
          compatibleAngles: ['medium-close / frontal', 'dutch-angle / dynamic'],
          compatibleWardrobe: ['charcoal hoodie'],
        },
        {
          id: 'pose_crossed_arms',
          name: 'Skeptical Crossed Arms',
          canonicalImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=600&auto=format&fit=crop',
          category: 'standing',
          landmarks: 'Forearms interlocked across chest, weight shifted onto left heel',
          semanticTags: ['skeptical', 'defensive', 'analytical', 'standing'],
          compatibleAngles: ['medium / frontal', 'three-quarter / low-angle'],
          compatibleWardrobe: ['charcoal hoodie', 'bomber jacket'],
        },
        {
          id: 'pose_holding_coffee',
          name: 'Espresso Sip & Stare',
          canonicalImage: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=600&auto=format&fit=crop',
          category: 'action',
          landmarks: 'Right hand holding ceramic mug at chest height, head tilted 5 deg',
          semanticTags: ['morning', 'coffee', 'introspection', 'chill'],
          compatibleAngles: ['close-up / eye-level', 'medium-close / profile'],
          compatibleWardrobe: ['charcoal hoodie'],
        },
      ],
      expressionLibrary: [
        { id: 'exp_deadpan', name: 'Deadpan Flat', canonicalImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=600&auto=format&fit=crop', emotion: 'deadpan', intensity: 8, semanticTags: ['signature', 'serious', 'humor'] },
        { id: 'exp_smug', name: 'Asymmetrical Smirk', canonicalImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=600&auto=format&fit=crop', emotion: 'smug', intensity: 7, semanticTags: ['irony', 'gotcha', 'confidence'] },
        { id: 'exp_confused', name: 'Mild Disbelief Eyebrow', canonicalImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=600&auto=format&fit=crop', emotion: 'confused', intensity: 6, semanticTags: ['questioning', 'observation'] },
        { id: 'exp_happy', name: 'Subtle Contented Smile', canonicalImage: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=600&auto=format&fit=crop', emotion: 'happy', intensity: 5, semanticTags: ['rare', 'warm', 'resolution'] },
      ],
      qaProfile: {
        identityThreshold: 0.88,
        allowedPoseVariance: 0.12,
        paletteDriftMax: 0.05,
        landmarkDriftMax: 0.08,
        lufsTarget: -14.0,
        maxLipSyncDiscrepancyMs: 40,
      },
      vectorLandmarks: [
        { id: 'lm_jaw_tip', name: 'Mandible Apex Anchor', category: 'jaw', x: 0.502, y: 0.745, confidence: 0.99 },
        { id: 'lm_jaw_left', name: 'Left Mandible Corner', category: 'jaw', x: 0.365, y: 0.680, confidence: 0.98 },
        { id: 'lm_jaw_right', name: 'Right Mandible Corner', category: 'jaw', x: 0.638, y: 0.680, confidence: 0.98 },
        { id: 'lm_brow_left', name: 'Left Eyebrow Crest', category: 'eyebrow', x: 0.410, y: 0.380, confidence: 0.97 },
        { id: 'lm_brow_right', name: 'Right Eyebrow Crest', category: 'eyebrow', x: 0.590, y: 0.380, confidence: 0.97 },
        { id: 'lm_eye_pupil_l', name: 'Left Eye Pupil', category: 'eye_pupil', x: 0.420, y: 0.435, confidence: 0.99 },
        { id: 'lm_eye_pupil_r', name: 'Right Eye Pupil', category: 'eye_pupil', x: 0.580, y: 0.435, confidence: 0.99 },
        { id: 'lm_mouth_upper', name: 'Upper Lip Anchor (Viseme)', category: 'mouth_viseme', x: 0.500, y: 0.640, confidence: 0.99 },
        { id: 'lm_mouth_lower', name: 'Lower Lip Anchor (Viseme)', category: 'mouth_viseme', x: 0.500, y: 0.685, confidence: 0.99 },
        { id: 'lm_bone_neck', name: 'Cervical Spine Origin', category: 'skeleton_bone', x: 0.500, y: 0.810, confidence: 0.95 },
        { id: 'lm_bone_shoulder_l', name: 'Left Acromion Joint', category: 'skeleton_bone', x: 0.280, y: 0.880, confidence: 0.94 },
        { id: 'lm_bone_shoulder_r', name: 'Right Acromion Joint', category: 'skeleton_bone', x: 0.720, y: 0.880, confidence: 0.94 },
      ],
    },
    {
      version: 'v3.1',
      characterId: 'char_milo',
      parentVersion: 'v2.0',
      createdAt: '2026-08-05T10:15:00Z',
      changeSummary: 'Initial v3 styling baseline; darker hair color palette and updated pose references.',
      isLocked: true,
      visualDna: {
        face: 'Angular jawline, light stubble',
        hair: 'Dark brown textured taper',
        hairColor: '#3A2720',
        skin: 'Warm olive',
        eyes: 'Hazel hooded',
        eyeColor: '#7A5C3D',
        bodyProportions: '6ft, athletic lean',
        wardrobe: 'Dark gray oversized hoodie',
        accessories: ['Headphones'],
        artStyle: 'Stylized realism',
        palette: ['#22262C', '#3A2720', '#FF9F24'],
        lineStyle: 'Clean silhouette',
        shading: 'Studio contrast',
        visualConstraints: ['No smile teeth'],
      },
      voiceProfile: {
        provider: 'ElevenLabs',
        voiceId: 'eleven_milo_v3_1',
        voiceName: 'Milo Vance v3.1',
        language: 'en-US',
        accent: 'Mid-Atlantic',
        pitch: 0.95,
        speakingSpeed: 1.0,
        emotionalProfile: 'Deadpan',
        stability: 0.75,
        similarityBoost: 0.8,
      },
      references: [],
      poseLibrary: [],
      expressionLibrary: [],
    },
    {
      version: 'v2.0',
      characterId: 'char_milo',
      createdAt: '2026-07-12T09:00:00Z',
      changeSummary: 'Legacy anime-influenced line style before photoreal consolidation.',
      isLocked: true,
      visualDna: {
        face: 'Anime-styled pointed chin',
        hair: 'Spiky brown hair',
        hairColor: '#4A3525',
        skin: 'Fair',
        eyes: 'Large amber eyes',
        eyeColor: '#9C6F44',
        bodyProportions: 'Slender',
        wardrobe: 'Black zip jacket',
        accessories: [],
        artStyle: 'Semi-realistic cell shading',
        palette: ['#1A1A1A', '#4A3525'],
        lineStyle: 'Crisp 2px vector line',
        shading: 'Cell shaded',
        visualConstraints: [],
      },
      voiceProfile: {
        provider: 'LocalTTS',
        voiceId: 'local_tts_milo',
        voiceName: 'Milo Legacy',
        language: 'en-US',
        accent: 'Neutral',
        pitch: 1.0,
        speakingSpeed: 1.0,
        emotionalProfile: 'Neutral',
        stability: 0.7,
        similarityBoost: 0.7,
      },
      references: [],
      poseLibrary: [],
      expressionLibrary: [],
    },
  ],
};

export const ZARA_CHARACTER: Character = {
  id: 'char_zara',
  name: 'Zara Chen',
  aliases: ['Zara', 'The Catalyst'],
  ageBracket: '25-28',
  archetype: 'High-Energy Skeptic & Tech Visionary',
  personality: 'Rapid-fire delivery, sharp wit, deeply analytical, hyper-organized foil to Milo.',
  role: 'Co-Host / Debate Partner',
  description: 'Fast-talking tech researcher who challenges Milo’s existential cynicism with hard data.',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=600&auto=format&fit=crop',
  currentVersion: 'v2.1',
  versions: [
    {
      version: 'v2.1',
      characterId: 'char_zara',
      createdAt: '2026-08-15T11:00:00Z',
      changeSummary: 'Added neon violet highlight to bob haircut and refined sharp blazer wardrobe.',
      isLocked: true,
      visualDna: {
        face: 'Symmetrical high cheekbones, razor-sharp jawline, bold structured brows',
        hair: 'Sleek jet-black asymmetrical bob with subtle neon violet edge sheen',
        hairColor: '#0E0F14',
        skin: 'Porcelain neutral with high clarity',
        eyes: 'Intense obsidian dark brown with sharp winged eyeliner',
        eyeColor: '#1A110B',
        bodyProportions: '5ft 7in, sharp posture, commanding stance',
        wardrobe: 'Tailored oversized minimalist blazer over crisp mock-neck top in obsidian black',
        accessories: ['Geometric titanium wire glasses', 'Minimalist ear cuff'],
        artStyle: 'High-contrast editorial cinematic',
        palette: ['#0E0F14', '#8B5CF6', '#F8FAFC', '#38BDF8'],
        lineStyle: 'Ultra-crisp razor silhouettes',
        shading: 'Dramatic split lighting with cool violet rim',
        visualConstraints: ['Glasses must remain on face in 95% of shots', 'Posture must remain upright and commanding'],
      },
      voiceProfile: {
        provider: 'ElevenLabs',
        voiceId: 'eleven_zara_v2_1',
        voiceName: 'Zara Chen (Crisp Articulate Alto)',
        language: 'en-US',
        accent: 'Pacific West Coast Articulate',
        pitch: 1.05,
        speakingSpeed: 1.18,
        emotionalProfile: 'Electrifying, brisk, mathematically precise cadence',
        stability: 0.82,
        similarityBoost: 0.88,
      },
      references: [],
      poseLibrary: [
        {
          id: 'pose_tablet_gesture',
          name: 'Data Point Demonstration',
          canonicalImage: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=600&auto=format&fit=crop',
          category: 'gesture',
          landmarks: 'Holding slate in left hand, right hand swiping invisible interface',
          semanticTags: ['data', 'explaining', 'confident'],
          compatibleAngles: ['medium / frontal', 'eye-level / three-quarter'],
          compatibleWardrobe: ['black blazer'],
        },
      ],
      expressionLibrary: [
        { id: 'exp_zara_smirk', name: 'Intellectual Triumph Smirk', canonicalImage: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=600&auto=format&fit=crop', emotion: 'smug', intensity: 9, semanticTags: ['victory', 'factcheck'] },
      ],
    },
  ],
};

export const KITO_CHARACTER: Character = {
  id: 'char_kito',
  name: 'Kito Alvarez',
  aliases: ['Kito', 'The Pragmatist'],
  ageBracket: '30-34',
  archetype: 'Easygoing Specialist & Sound Engineer',
  personality: 'Calm, unflappable, warm baritone, grounds discussions with real-world practical insight.',
  role: 'Ensemble Specialist',
  description: 'The studio veteran who keeps Milo and Zara from spinning out into endless theoretical debates.',
  avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=600&auto=format&fit=crop',
  currentVersion: 'v1.4',
  versions: [
    {
      version: 'v1.4',
      characterId: 'char_kito',
      createdAt: '2026-08-10T16:00:00Z',
      changeSummary: 'Standard studio wardrobe and warm amber studio backlighting.',
      isLocked: true,
      visualDna: {
        face: 'Warm rounded jaw, trimmed neat beard, gentle smile lines around eyes',
        hair: 'Short faded curls in warm espresso black',
        hairColor: '#1A1817',
        skin: 'Rich warm bronze with natural studio luster',
        eyes: 'Deep warm espresso brown, attentive friendly gaze',
        eyeColor: '#2B1810',
        bodyProportions: '6ft 1in, broad shoulders, grounded relaxed stance',
        wardrobe: 'Olive green utility overshirt over heather gray vintage tee',
        accessories: ['Leather band mechanical watch'],
        artStyle: 'Warm cinematic portraiture',
        palette: ['#4A5568', '#48BB78', '#D69E2E', '#2D3748'],
        lineStyle: 'Natural organic contours',
        shading: 'Warm tungsten interior bounce',
        visualConstraints: ['Beard must stay neatly groomed'],
      },
      voiceProfile: {
        provider: 'ElevenLabs',
        voiceId: 'eleven_kito_v1_4',
        voiceName: 'Kito Alvarez (Warm Resonant Baritone)',
        language: 'en-US',
        accent: 'American Southwest Chill',
        pitch: 0.88,
        speakingSpeed: 0.95,
        emotionalProfile: 'Reassuring, grounded, measured cadence',
        stability: 0.88,
        similarityBoost: 0.9,
      },
      references: [],
      poseLibrary: [],
      expressionLibrary: [],
    },
  ],
};

export const CANONICAL_UNIVERSE: Universe = {
  id: 'universe_milo_chronicles',
  name: 'The Milo Chronicles',
  description: 'A persistent cinematic universe exploring modern work, digital hyper-optimization, and existential comedy.',
  characters: [MILO_CHARACTER, ZARA_CHARACTER, KITO_CHARACTER],
  locations: INITIAL_LOCATIONS,
  props: INITIAL_PROPS,
  lore: [
    'The trio operates an underground independent broadcasting lab in a converted loft above the city.',
    'Milo drinks precisely 3 quad-espressos before 11 AM.',
    'Zara tracks every debate win in an encrypted SQLite database.',
    'Kito secretly wrote the ambient synthesizer soundtrack for the entire studio.',
  ],
  visualStyle: 'Dark luxury cinematic with warm gold (#FF9F24) key accents, razor edge silhouettes, and rich photographic contrast.',
  rules: [
    'Every production must maintain locked character visual DNA versioning.',
    'Never allow character appearance to mutate between scenes.',
    'Audio LUFS must normalize to -14.0 LUFS with zero digital clipping.',
    'Motion generation must pass landmark drift QA before composite staging.',
  ],
  recipes: [
    {
      id: 'recipe_comedy_short',
      name: 'Viral Satire / Comedy Short (6-Stage)',
      category: 'comedy_short',
      description: 'High-velocity format with hook provocation, rapid escalation, deadpan observation, and sharp punchline resolution.',
      targetDuration: 22,
      structure: [
        { stage: 'hook', label: 'Provocative Hook Rule', suggestedCamera: 'medium / eye-level', suggestedEmotion: 'deadpan', durationRatio: 0.22, guideline: 'Challenge a popular modern ritual with bold contrarian irony.' },
        { stage: 'setup', label: 'Cultural Observation', suggestedCamera: 'close-up / 45-deg', suggestedEmotion: 'confused', durationRatio: 0.22, guideline: 'Paint the ridiculous mental picture of common behavior.' },
        { stage: 'conflict', label: 'Personal Vulnerability', suggestedCamera: 'medium-close / profile', suggestedEmotion: 'deadpan', durationRatio: 0.20, guideline: 'Contrast the cultural pressure with real human limitation.' },
        { stage: 'observation', label: 'Philosophical Axiom', suggestedCamera: 'three-quarter / low-angle', suggestedEmotion: 'smug', durationRatio: 0.18, guideline: 'Deliver the core thesis like an immutable natural law.' },
        { stage: 'punchline', label: 'Decisive Punchline', suggestedCamera: 'close-up / eye-level', suggestedEmotion: 'deadpan', durationRatio: 0.12, guideline: 'Wrap with tight comedic reversal.' },
        { stage: 'cta', label: 'Minimalist Sign-off', suggestedCamera: 'medium / frontal', suggestedEmotion: 'happy', durationRatio: 0.06, guideline: 'Direct tap-to-follow or community prompt.' },
      ],
    },
    {
      id: 'recipe_educational_teardown',
      name: 'System Architecture Breakdown',
      category: 'educational_breakdown',
      description: 'Clear, high-retention technical dissection of complex systems with vector overlays and precise dialogue.',
      targetDuration: 30,
      structure: [
        { stage: 'hook', label: 'Core Problem Statement', suggestedCamera: 'medium / frontal', suggestedEmotion: 'serious', durationRatio: 0.15, guideline: 'State the costly bottleneck or naive assumption.' },
        { stage: 'setup', label: 'Architectural Fallacy', suggestedCamera: 'three-quarter / low-angle', suggestedEmotion: 'analytical', durationRatio: 0.25, guideline: 'Deconstruct why traditional approaches break down.' },
        { stage: 'observation', label: 'First Principles Solution', suggestedCamera: 'close-up / eye-level', suggestedEmotion: 'confident', durationRatio: 0.35, guideline: 'Demonstrate the exact structural breakthrough.' },
        { stage: 'punchline', label: 'Actionable Takeaway', suggestedCamera: 'medium / eye-level', suggestedEmotion: 'neutral', durationRatio: 0.25, guideline: 'Summary rule to implement immediately.' },
      ],
    },
  ],
};

export const INITIAL_EPISODES: Episode[] = [
  {
    id: 'ep_gym_ego',
    universeId: 'universe_milo_chronicles',
    title: 'Episode 14 — Gym Ego & The 4 AM Myth',
    premise: 'Milo dissects why modern hustle culture treats 4 AM gym sessions like a cheat code to enlightenment.',
    objective: 'Create a viral, high-retention 22-second short dissecting hustle myths with sharp punchlines.',
    targetDuration: 22,
    platform: 'tiktok_shorts_reels',
    aspectRatio: '9:16',
    version: 'v2.4',
    createdAt: '2026-08-25T10:00:00Z',
    updatedAt: '2026-08-29T16:20:00Z',
    script: {
      rawText: `Rule number one of modern fitness: You didn't work out unless someone at 4:30 AM saw you suffer.
Everyone is out here looking like gladiators fighting imaginary spreadsheets.
Meanwhile, I'm just trying to negotiate peace with my lower back.
Consistency beats performative intensity every single day.`,
      mode: 'template',
      templateType: 'commentary',
      structure: {
        hook: "Rule number one of modern fitness: You didn't work out unless someone at 4:30 AM saw you suffer.",
        setup: "Everyone is out here looking like gladiators fighting imaginary spreadsheets.",
        conflict: "Meanwhile, I'm just trying to negotiate peace with my lower back.",
        observation: "If suffering was a currency, gym influencers would be running central banks.",
        punchline: "Consistency beats performative intensity every single day.",
        cta: "Save your spine. Tap follow.",
      },
    },
    scenes: [
      {
        id: 'scene_gym_open',
        sceneNumber: 1,
        title: 'Opening & Hook at the Rack',
        locationId: 'loc_cyber_gym',
        shots: [
          {
            id: 'shot_001',
            shotNumber: 1,
            characterId: 'char_milo',
            characterVersion: 'v3.2',
            poseId: 'pose_bench_slouch',
            expressionId: 'exp_deadpan',
            action: 'holding_coffee',
            locationId: 'loc_cyber_gym',
            camera: 'medium / eye-level',
            dialogue: "Rule number one of modern fitness: You didn't work out unless someone at 4:30 AM saw you suffer.",
            emotion: 'deadpan',
            duration: 4.8,
            motionPreset: 'subtle_head',
            propIds: ['prop_espresso_cup'],
            referenceAssetHashes: ['sha256:88fa29e81'],
            seed: 1042,
            status: 'COMPLETED',
            primaryProvider: 'Flux.1-Dev-Adapter',
            fallbackStrategy: 'static_pose_animation',
            generatedArtifacts: {
              baseImageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=600&auto=format&fit=crop',
              audioUrl: 'mock_audio_shot_001.wav',
              motionClipUrl: 'mock_motion_shot_001.mp4',
              qaResult: {
                identityStatus: 'PASS',
                identityScore: 0.94,
                visualStatus: 'PASS',
                visualArtifactsDetected: [],
                audioStatus: 'PASS',
                audioMetrics: { peakDb: -1.2, rmsDb: -16.4, lufs: -14.1, silenceDetected: false, clippingDetected: false },
                motionStatus: 'PASS',
                motionDriftDetected: false,
                compositeStatus: 'PASS',
                overallStatus: 'PASS',
              },
            },
          },
          {
            id: 'shot_002',
            shotNumber: 2,
            characterId: 'char_milo',
            characterVersion: 'v3.2',
            poseId: 'pose_pointing_forward',
            expressionId: 'exp_smug',
            action: 'gesturing_towards_weights',
            locationId: 'loc_cyber_gym',
            camera: 'close-up / dutch-angle',
            dialogue: "Everyone is out here looking like gladiators fighting imaginary spreadsheets.",
            emotion: 'smug',
            duration: 4.5,
            motionPreset: 'hand_emphasis',
            propIds: [],
            referenceAssetHashes: ['sha256:77bc34e12'],
            seed: 1043,
            status: 'COMPLETED',
            primaryProvider: 'Flux.1-Dev-Adapter',
            fallbackStrategy: 'static_pose_animation',
            generatedArtifacts: {
              baseImageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=600&auto=format&fit=crop',
              audioUrl: 'mock_audio_shot_002.wav',
              motionClipUrl: 'mock_motion_shot_002.mp4',
              qaResult: {
                identityStatus: 'PASS',
                identityScore: 0.91,
                visualStatus: 'PASS',
                visualArtifactsDetected: [],
                audioStatus: 'PASS',
                audioMetrics: { peakDb: -0.8, rmsDb: -15.8, lufs: -13.9, silenceDetected: false, clippingDetected: false },
                motionStatus: 'PASS',
                motionDriftDetected: false,
                compositeStatus: 'PASS',
                overallStatus: 'PASS',
              },
            },
          },
        ],
      },
      {
        id: 'scene_coffee_contrast',
        sceneNumber: 2,
        title: 'Contrast & Reality Check',
        locationId: 'loc_coffee_shop',
        shots: [
          {
            id: 'shot_003',
            shotNumber: 3,
            characterId: 'char_milo',
            characterVersion: 'v3.2',
            poseId: 'pose_holding_coffee',
            expressionId: 'exp_confused',
            action: 'observing_coffee_drip',
            locationId: 'loc_coffee_shop',
            camera: 'medium / eye-level',
            dialogue: "Meanwhile, I'm just trying to negotiate peace with my lower back over a double espresso.",
            emotion: 'confused',
            duration: 5.2,
            motionPreset: 'subtle_head',
            propIds: ['prop_espresso_cup'],
            referenceAssetHashes: ['sha256:88fa29e81'],
            seed: 1044,
            status: 'COMPLETED',
            primaryProvider: 'Flux.1-Dev-Adapter',
            fallbackStrategy: 'camera_motion_fallback',
            generatedArtifacts: {
              baseImageUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=600&auto=format&fit=crop',
              audioUrl: 'mock_audio_shot_003.wav',
              motionClipUrl: 'mock_motion_shot_003.mp4',
              qaResult: {
                identityStatus: 'PASS',
                identityScore: 0.89,
                visualStatus: 'PASS',
                visualArtifactsDetected: [],
                audioStatus: 'PASS',
                audioMetrics: { peakDb: -1.5, rmsDb: -17.0, lufs: -14.2, silenceDetected: false, clippingDetected: false },
                motionStatus: 'WARNING',
                motionDriftDetected: true,
                driftFrames: 'Frames 78-92 slight jawline tremor',
                remedyAction: 'Applied subtle anchor smoothing filter',
                compositeStatus: 'PASS',
                overallStatus: 'WARNING',
              },
            },
          },
          {
            id: 'shot_004',
            shotNumber: 4,
            characterId: 'char_milo',
            characterVersion: 'v3.2',
            poseId: 'pose_crossed_arms',
            expressionId: 'exp_happy',
            action: 'direct_punchline_delivery',
            locationId: 'loc_sunset_rooftop',
            camera: 'medium-close / frontal',
            dialogue: "Remember: Consistency beats performative intensity every single time.",
            emotion: 'happy',
            duration: 4.5,
            motionPreset: 'talking_neutral',
            propIds: [],
            referenceAssetHashes: ['sha256:99ff20a33'],
            seed: 1045,
            status: 'COMPLETED',
            primaryProvider: 'Flux.1-Dev-Adapter',
            fallbackStrategy: 'static_pose_animation',
            generatedArtifacts: {
              baseImageUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=600&auto=format&fit=crop',
              audioUrl: 'mock_audio_shot_004.wav',
              motionClipUrl: 'mock_motion_shot_004.mp4',
              qaResult: {
                identityStatus: 'PASS',
                identityScore: 0.95,
                visualStatus: 'PASS',
                visualArtifactsDetected: [],
                audioStatus: 'PASS',
                audioMetrics: { peakDb: -1.0, rmsDb: -16.2, lufs: -14.0, silenceDetected: false, clippingDetected: false },
                motionStatus: 'PASS',
                motionDriftDetected: false,
                compositeStatus: 'PASS',
                overallStatus: 'PASS',
              },
            },
          },
        ],
      },
    ],
  },
  {
    id: 'ep_coffee_paradox',
    universeId: 'universe_milo_chronicles',
    title: 'Episode 15 — The Coffee Machine Paradox',
    premise: 'Milo and Zara debate why an espresso machine with 14 dials makes worse coffee than an old moka pot.',
    objective: 'Produce a 2-character dialogue short highlighting tech over-engineering.',
    targetDuration: 28,
    platform: 'youtube_landscape',
    aspectRatio: '16:9',
    version: 'v1.0',
    createdAt: '2026-08-27T14:00:00Z',
    updatedAt: '2026-08-28T18:00:00Z',
    script: {
      rawText: `Milo: Zara, why does this $3,000 espresso machine require a Wi-Fi firmware update just to steam milk?
Zara: Because optimal extraction temperature requires millimeter-level thermal PID feedback.
Milo: My grandmother used a tin pot on an open flame and her coffee could resurrect ancient civilizations.
Zara: Your grandmother drank charcoal and nostalgia.`,
      mode: 'manual',
      structure: {
        hook: "Why does this espresso machine require a Wi-Fi firmware update?",
        setup: "Zara defends thermal PID loops while Milo points out the absurdity.",
        conflict: "Modern high-tech gadgets vs ancient reliable simplicity.",
        observation: "More dials correlate directly with slower mornings.",
        punchline: "Charcoal and nostalgia beats a 404 error on your breakfast.",
        cta: "What's your coffee setup? Tell us below.",
      },
    },
    scenes: [
      {
        id: 'scene_coffee_lab',
        sceneNumber: 1,
        title: 'Espresso Counter Debate',
        locationId: 'loc_coffee_shop',
        shots: [
          {
            id: 'shot_cp_01',
            shotNumber: 1,
            characterId: 'char_milo',
            characterVersion: 'v3.2',
            poseId: 'pose_bench_slouch',
            expressionId: 'exp_confused',
            action: 'pointing_at_machine',
            locationId: 'loc_coffee_shop',
            camera: 'medium / eye-level',
            dialogue: "Why does this $3,000 machine require a Wi-Fi firmware update to steam milk?",
            emotion: 'confused',
            duration: 5.5,
            motionPreset: 'subtle_head',
            propIds: ['prop_espresso_cup'],
            referenceAssetHashes: ['sha256:88fa29e81'],
            seed: 2011,
            status: 'READY',
            primaryProvider: 'Flux.1-Dev-Adapter',
            fallbackStrategy: 'static_pose_animation',
          },
          {
            id: 'shot_cp_02',
            shotNumber: 2,
            characterId: 'char_zara',
            characterVersion: 'v2.1',
            poseId: 'pose_tablet_gesture',
            expressionId: 'exp_zara_smirk',
            action: 'gesturing_with_tablet',
            locationId: 'loc_coffee_shop',
            camera: 'medium-close / profile',
            dialogue: "Because optimal extraction requires millimeter thermal PID feedback, Milo.",
            emotion: 'smug',
            duration: 5.0,
            motionPreset: 'talking_neutral',
            propIds: ['prop_smart_pad'],
            referenceAssetHashes: ['sha256:77bc34e12'],
            seed: 2012,
            status: 'READY',
            primaryProvider: 'Flux.1-Dev-Adapter',
            fallbackStrategy: 'static_pose_animation',
          },
        ],
      },
    ],
  },
];

export const PROVIDER_REGISTRY: ProviderAdapter[] = [
  {
    id: 'prv_flux',
    name: 'Flux.1-Dev Production Adapter',
    type: 'visual',
    models: ['flux-1-dev-fp8', 'flux-1-schnell', 'flux-pro-v1.1'],
    selectedModel: 'flux-1-dev-fp8',
    isAvailable: true,
    capabilities: {
      supportsReferenceImages: true,
      supportsCharacterLora: true,
      supportsSeed: true,
      supportsPoseControl: true,
      supportsExpressionControl: true,
      supportsAudioDriving: false,
      supportsVisemes: false,
      supportsStreaming: false,
      supportsAsyncGeneration: true,
      maxResolution: '2048x2048',
      estimatedCostPerUnit: 0.024,
      estimatedLatencyMs: 1400,
    },
  },
  {
    id: 'prv_elevenlabs',
    name: 'ElevenLabs Voice Engine Adapter',
    type: 'voice',
    models: ['eleven_turbo_v2_5', 'eleven_multilingual_v2', 'eleven_monolingual_v1'],
    selectedModel: 'eleven_multilingual_v2',
    isAvailable: true,
    capabilities: {
      supportsReferenceImages: false,
      supportsCharacterLora: false,
      supportsSeed: true,
      supportsPoseControl: false,
      supportsExpressionControl: false,
      supportsAudioDriving: true,
      supportsVisemes: true,
      supportsStreaming: true,
      supportsAsyncGeneration: true,
      maxResolution: '48kHz PCM',
      estimatedCostPerUnit: 0.015,
      estimatedLatencyMs: 850,
    },
  },
  {
    id: 'prv_liveportrait',
    name: 'LivePortrait Motion Adapter',
    type: 'motion',
    models: ['liveportrait-fp16-v1.2', 'liveportrait-enhanced-exp', 'static-camera-pan-fallback'],
    selectedModel: 'liveportrait-fp16-v1.2',
    isAvailable: true,
    capabilities: {
      supportsReferenceImages: true,
      supportsCharacterLora: false,
      supportsSeed: true,
      supportsPoseControl: true,
      supportsExpressionControl: true,
      supportsAudioDriving: true,
      supportsVisemes: true,
      supportsStreaming: false,
      supportsAsyncGeneration: true,
      maxResolution: '1920x1080',
      estimatedCostPerUnit: 0.035,
      estimatedLatencyMs: 2200,
    },
  },
  {
    id: 'prv_gemini',
    name: 'Gemini 3.7 Flash Intelligence Adapter',
    type: 'llm',
    models: ['gemini-3.7-flash', 'gemini-3.1-flash-lite'],
    selectedModel: 'gemini-3.7-flash',
    isAvailable: true,
    capabilities: {
      supportsReferenceImages: true,
      supportsCharacterLora: false,
      supportsSeed: true,
      supportsPoseControl: false,
      supportsExpressionControl: false,
      supportsAudioDriving: false,
      supportsVisemes: false,
      supportsStreaming: true,
      supportsAsyncGeneration: false,
      maxResolution: 'Structured JSON / Schema',
      estimatedCostPerUnit: 0.002,
      estimatedLatencyMs: 400,
    },
  },
];

export const INITIAL_ASSET_LINEAGE: AssetLineageRecord[] = [
  {
    assetId: 'ast_img_milo_01',
    type: 'IMAGE',
    version: 'v3.2',
    hash: 'sha256:88fa29e81c00941',
    storageUri: 'assets/images/milo_v3.2_bench_slouch.webp',
    mimeType: 'image/webp',
    width: 1080,
    height: 1920,
    createdAt: '2026-08-25T10:02:14Z',
    provider: 'Flux.1-Dev-Adapter',
    model: 'flux-1-dev-fp8',
    generationMetadata: { seed: 1042, steps: 28, guidance: 3.5 },
    parentAssets: ['sha256:88fa29e81', 'ref_milo_front'],
    characterVersionRef: 'char_milo@v3.2',
    cacheKey: 'sha256:7f082e01b44b8e',
  },
  {
    assetId: 'ast_aud_milo_01',
    type: 'AUDIO',
    version: 'v3.2',
    hash: 'sha256:12bc880291afb49',
    storageUri: 'assets/audio/shot_001_voice.wav',
    mimeType: 'audio/wav',
    duration: 4.8,
    createdAt: '2026-08-25T10:02:16Z',
    provider: 'ElevenLabs',
    model: 'eleven_multilingual_v2',
    generationMetadata: { stability: 0.78, similarity: 0.85, lufs: -14.1 },
    parentAssets: ['char_milo@v3.2'],
    characterVersionRef: 'char_milo@v3.2',
    cacheKey: 'sha256:810488ae77c28b',
  },
  {
    assetId: 'ast_vid_milo_01',
    type: 'VIDEO',
    version: 'v3.2',
    hash: 'sha256:99014ba0821ccde',
    storageUri: 'assets/video/shot_001_motion.mp4',
    mimeType: 'video/mp4',
    width: 1080,
    height: 1920,
    duration: 4.8,
    createdAt: '2026-08-25T10:02:22Z',
    provider: 'LivePortrait',
    model: 'liveportrait-fp16-v1.2',
    generationMetadata: { driver: 'ast_aud_milo_01', landmarkIntegrity: 0.96 },
    parentAssets: ['ast_img_milo_01', 'ast_aud_milo_01'],
    characterVersionRef: 'char_milo@v3.2',
    cacheKey: 'sha256:44ba7701e82811',
  },
  {
    assetId: 'ast_final_render_ep14',
    type: 'FINAL_RENDER',
    version: 'v2.4',
    hash: 'sha256:ef44990192841bc',
    storageUri: 'output/ep14_gym_ego_final.mp4',
    mimeType: 'video/mp4',
    width: 1080,
    height: 1920,
    duration: 19.0,
    createdAt: '2026-08-25T10:03:00Z',
    provider: 'TSICVIDIA-FFmpeg-Compositor',
    model: 'ffmpeg-7.0-master',
    generationMetadata: { codec: 'h264', audioCodec: 'aac', bitrate: '12M', lufs: -14.0 },
    parentAssets: ['ast_vid_milo_01', 'ast_vid_milo_02', 'ast_vid_milo_03', 'ast_vid_milo_04'],
    characterVersionRef: 'char_milo@v3.2',
    cacheKey: 'sha256:manifest_gym_ego_locked',
  },
];
